apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec: 
      containers:
      - name: front-end
        image: prostotema1/repoforbpproject:front-end
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: prostotema1/repoforbpproject:backend
        ports:
        - containerPort: 8080
      - name : database
        image: prostotema1/repoforbpproject:database
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: back-end-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: /back
          backend:
            service:
              name: back-end-service
              port:
                number: 8080
        - pathType: Prefix
          path: /
          backend:
            service:
              name: front-end-service
              port:
                number: 80
